---
- name: Ensure app directory exists
  file:
    path: "/usr/local/lib/my_api"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'
  tags: 
    - app

- name: Create systemd unit for app
  register: service_unit_added
  template:
    src: "{{ playbook_dir }}/templates/my_api.j2"
    dest: "/etc/systemd/system/my_api.service"
    owner: root
    group: root
    mode: "0755"
  tags: 
    - app

- name: Enable service unit
  when: service_unit_added is changed
  systemd:
    name: my_api
    enabled: yes
  tags: 
    - app

- name: Reload daemons
  systemd:
    daemon_reload: true
  ignore_errors: yes
  tags: 
    - app

- name: Enable service unit
  command: "systemctl restart my_api"
  ignore_errors: yes
  tags: 
    - app